#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MM_Intro

#include "Basic.hpp"

#include "MM_Intro_classes.hpp"
#include "MM_Intro_parameters.hpp"


namespace SDK
{

// Function MM_Intro.MM_Intro_C.ExecuteUbergraph_MM_Intro
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMM_Intro_C::ExecuteUbergraph_MM_Intro(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MM_Intro_C", "ExecuteUbergraph_MM_Intro");

	Params::MM_Intro_C_ExecuteUbergraph_MM_Intro Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MM_Intro.MM_Intro_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UMM_Intro_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MM_Intro_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MM_Intro.MM_Intro_C.IntroExit
// (BlueprintCallable, BlueprintEvent)

void UMM_Intro_C::IntroExit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MM_Intro_C", "IntroExit");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MM_Intro.MM_Intro_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMM_Intro_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MM_Intro_C", "Tick");

	Params::MM_Intro_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MM_Intro.MM_Intro_C.OpenProfileCreationFailed
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UMM_Intro_C::OpenProfileCreationFailed(const class FText& InText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MM_Intro_C", "OpenProfileCreationFailed");

	Params::MM_Intro_C_OpenProfileCreationFailed Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MM_Intro.MM_Intro_C.BndEvt__MM_Intro_RetryProfileCreation_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMM_Intro_C::BndEvt__MM_Intro_RetryProfileCreation_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MM_Intro_C", "BndEvt__MM_Intro_RetryProfileCreation_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MM_Intro.MM_Intro_C.BndEvt__MM_Intro_CreateProfile_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMM_Intro_C::BndEvt__MM_Intro_CreateProfile_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MM_Intro_C", "BndEvt__MM_Intro_CreateProfile_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MM_Intro.MM_Intro_C.CheckCreateProfileButtonEnabled
// (BlueprintCallable, BlueprintEvent)

void UMM_Intro_C::CheckCreateProfileButtonEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MM_Intro_C", "CheckCreateProfileButtonEnabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MM_Intro.MM_Intro_C.BndEvt__MM_Intro_Region_K2Node_ComponentBoundEvent_4_OnSelectionChangedEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class FString                           SelectedItem                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// ESelectInfo                             SelectionType                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMM_Intro_C::BndEvt__MM_Intro_Region_K2Node_ComponentBoundEvent_4_OnSelectionChangedEvent__DelegateSignature(const class FString& SelectedItem, ESelectInfo SelectionType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MM_Intro_C", "BndEvt__MM_Intro_Region_K2Node_ComponentBoundEvent_4_OnSelectionChangedEvent__DelegateSignature");

	Params::MM_Intro_C_BndEvt__MM_Intro_Region_K2Node_ComponentBoundEvent_4_OnSelectionChangedEvent__DelegateSignature Parms{};

	Parms.SelectedItem = std::move(SelectedItem);
	Parms.SelectionType = SelectionType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MM_Intro.MM_Intro_C.BndEvt__MM_Intro_Name_K2Node_ComponentBoundEvent_3_OnEditableTextBoxChangedEvent__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UMM_Intro_C::BndEvt__MM_Intro_Name_K2Node_ComponentBoundEvent_3_OnEditableTextBoxChangedEvent__DelegateSignature(const class FText& Text)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MM_Intro_C", "BndEvt__MM_Intro_Name_K2Node_ComponentBoundEvent_3_OnEditableTextBoxChangedEvent__DelegateSignature");

	Params::MM_Intro_C_BndEvt__MM_Intro_Name_K2Node_ComponentBoundEvent_3_OnEditableTextBoxChangedEvent__DelegateSignature Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MM_Intro.MM_Intro_C.OpenProfileCreation
// (BlueprintCallable, BlueprintEvent)

void UMM_Intro_C::OpenProfileCreation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MM_Intro_C", "OpenProfileCreation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MM_Intro.MM_Intro_C.BndEvt__MM_Intro_Warning_OK_K2Node_ComponentBoundEvent_2_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void UMM_Intro_C::BndEvt__MM_Intro_Warning_OK_K2Node_ComponentBoundEvent_2_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MM_Intro_C", "BndEvt__MM_Intro_Warning_OK_K2Node_ComponentBoundEvent_2_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MM_Intro.MM_Intro_C.OpenWarningScreen
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             InText                                                 (BlueprintVisible, BlueprintReadOnly, Parm)

void UMM_Intro_C::OpenWarningScreen(const class FText& InText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MM_Intro_C", "OpenWarningScreen");

	Params::MM_Intro_C_OpenWarningScreen Parms{};

	Parms.InText = std::move(InText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MM_Intro.MM_Intro_C.SkipIntro
// (BlueprintCallable, BlueprintEvent)

void UMM_Intro_C::SkipIntro()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MM_Intro_C", "SkipIntro");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MM_Intro.MM_Intro_C.BndEvt__MM_Intro_Yes_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMM_Intro_C::BndEvt__MM_Intro_Yes_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MM_Intro_C", "BndEvt__MM_Intro_Yes_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MM_Intro.MM_Intro_C.BndEvt__MM_Intro_No_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UMM_Intro_C::BndEvt__MM_Intro_No_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MM_Intro_C", "BndEvt__MM_Intro_No_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MM_Intro.MM_Intro_C.OpenLoginFailScreen
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Header_Message                                         (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             Param_DebugMessage                                     (BlueprintVisible, BlueprintReadOnly, Parm)
// ESlateVisibility                        DebugMessageVis                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// ESlateVisibility                        RetryButtonVis                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMM_Intro_C::OpenLoginFailScreen(const class FText& Header_Message, const class FText& Param_DebugMessage, ESlateVisibility DebugMessageVis, ESlateVisibility RetryButtonVis)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MM_Intro_C", "OpenLoginFailScreen");

	Params::MM_Intro_C_OpenLoginFailScreen Parms{};

	Parms.Header_Message = std::move(Header_Message);
	Parms.Param_DebugMessage = std::move(Param_DebugMessage);
	Parms.DebugMessageVis = DebugMessageVis;
	Parms.RetryButtonVis = RetryButtonVis;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MM_Intro.MM_Intro_C.Disable
// (BlueprintCallable, BlueprintEvent)

void UMM_Intro_C::Disable()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MM_Intro_C", "Disable");

	UObject::ProcessEvent(Func, nullptr);
}

}

