#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NewsItem

#include "Basic.hpp"

#include "NewsItem_classes.hpp"
#include "NewsItem_parameters.hpp"


namespace SDK
{

// Function NewsItem.NewsItem_C.ExecuteUbergraph_NewsItem
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UNewsItem_C::ExecuteUbergraph_NewsItem(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewsItem_C", "ExecuteUbergraph_NewsItem");

	Params::NewsItem_C_ExecuteUbergraph_NewsItem Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NewsItem.NewsItem_C.BndEvt__NewsItem_Button_56_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UNewsItem_C::BndEvt__NewsItem_Button_56_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewsItem_C", "BndEvt__NewsItem_Button_56_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NewsItem.NewsItem_C.RecieveNewArticle
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           NewsItemString                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UNewsItem_C::RecieveNewArticle(const class FString& NewsItemString)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NewsItem_C", "RecieveNewArticle");

	Params::NewsItem_C_RecieveNewArticle Parms{};

	Parms.NewsItemString = std::move(NewsItemString);

	UObject::ProcessEvent(Func, &Parms);
}

}

