#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PSO_GameInstance

#include "Basic.hpp"

#include "PSO_GameInstance_classes.hpp"
#include "PSO_GameInstance_parameters.hpp"


namespace SDK
{

// Function PSO_GameInstance.PSO_GameInstance_C.ExecuteUbergraph_PSO_GameInstance
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::ExecuteUbergraph_PSO_GameInstance(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "ExecuteUbergraph_PSO_GameInstance");

	Params::PSO_GameInstance_C_ExecuteUbergraph_PSO_GameInstance Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.2ndAppTicketLoop
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::TwondAppTicketLoop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "2ndAppTicketLoop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.InitialAppTicketLoop
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::InitialAppTicketLoop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "InitialAppTicketLoop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.StartAppTicketLoop
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::StartAppTicketLoop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "StartAppTicketLoop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.RefreshAppTicket
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::RefreshAppTicket()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "RefreshAppTicket");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.UpdateSteamNameSuccess
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVaRestRequestJSON*               Request                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::UpdateSteamNameSuccess(class UVaRestRequestJSON* Request)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "UpdateSteamNameSuccess");

	Params::PSO_GameInstance_C_UpdateSteamNameSuccess Parms{};

	Parms.Request = Request;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.UpdateSteamNameFail
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UVaRestRequestJSON*               Request                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::UpdateSteamNameFail(class UVaRestRequestJSON* Request)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "UpdateSteamNameFail");

	Params::PSO_GameInstance_C_UpdateSteamNameFail Parms{};

	Parms.Request = Request;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Save_PSO_PlayerAppearance
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FSP_PlayerAppearance             Param_SP_PlayerAppearance                              (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UPSO_GameInstance_C::Save_PSO_PlayerAppearance(const struct FSP_PlayerAppearance& Param_SP_PlayerAppearance)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Save_PSO_PlayerAppearance");

	Params::PSO_GameInstance_C_Save_PSO_PlayerAppearance Parms{};

	Parms.Param_SP_PlayerAppearance = std::move(Param_SP_PlayerAppearance);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Load_PSO_PlayerAppearance
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::Load_PSO_PlayerAppearance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Load_PSO_PlayerAppearance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Save_PSO_CustomTeam
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FCustomTeam                      Param_CustomTeam                                       (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void UPSO_GameInstance_C::Save_PSO_CustomTeam(const struct FCustomTeam& Param_CustomTeam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Save_PSO_CustomTeam");

	Params::PSO_GameInstance_C_Save_PSO_CustomTeam Parms{};

	Parms.Param_CustomTeam = std::move(Param_CustomTeam);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Load_PSO_CustomTeam
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::Load_PSO_CustomTeam()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Load_PSO_CustomTeam");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.StartNetProfiler
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::StartNetProfiler()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "StartNetProfiler");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckAchievements_All
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   GoalsThisGame                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::CheckAchievements_All(int32 GoalsThisGame)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckAchievements_All");

	Params::PSO_GameInstance_C_CheckAchievements_All Parms{};

	Parms.GoalsThisGame = GoalsThisGame;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckAchievements_Saves
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Saves                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::CheckAchievements_Saves(int32 Saves)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckAchievements_Saves");

	Params::PSO_GameInstance_C_CheckAchievements_Saves Parms{};

	Parms.Saves = Saves;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckAchievements_Wins
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Wins                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::CheckAchievements_Wins(int32 Wins)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckAchievements_Wins");

	Params::PSO_GameInstance_C_CheckAchievements_Wins Parms{};

	Parms.Wins = Wins;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.INTs
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Param_INTs                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::INTs(int32 Param_INTs)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "INTs");

	Params::PSO_GameInstance_C_INTs Parms{};

	Parms.Param_INTs = Param_INTs;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckAchievements_Matches
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Matches                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::CheckAchievements_Matches(int32 Matches)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckAchievements_Matches");

	Params::PSO_GameInstance_C_CheckAchievements_Matches Parms{};

	Parms.Matches = Matches;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckAchievements_Assists
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Assists                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::CheckAchievements_Assists(int32 Assists)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckAchievements_Assists");

	Params::PSO_GameInstance_C_CheckAchievements_Assists Parms{};

	Parms.Assists = Assists;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckAchievements_Goals
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Goals                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   GoalsThisGame                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::CheckAchievements_Goals(int32 Goals, int32 GoalsThisGame)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckAchievements_Goals");

	Params::PSO_GameInstance_C_CheckAchievements_Goals Parms{};

	Parms.Goals = Goals;
	Parms.GoalsThisGame = GoalsThisGame;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckAchievements_Passes
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Passes                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::CheckAchievements_Passes(int32 Passes)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckAchievements_Passes");

	Params::PSO_GameInstance_C_CheckAchievements_Passes Parms{};

	Parms.Passes = Passes;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Login
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UIntro_C*                         IntroMenu                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   LoginType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::Login(class UIntro_C* IntroMenu, int32 LoginType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Login");

	Params::PSO_GameInstance_C_Login Parms{};

	Parms.IntroMenu = IntroMenu;
	Parms.LoginType = LoginType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Set_RandomPSID
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::Set_RandomPSID()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Set_RandomPSID");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.ReceiveShutdown
// (Event, Public, BlueprintEvent)

void UPSO_GameInstance_C::ReceiveShutdown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "ReceiveShutdown");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.ReceiveInit
// (Event, Public, BlueprintEvent)

void UPSO_GameInstance_C::ReceiveInit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "ReceiveInit");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckVoteNoKeys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckVoteNoKeys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckVoteNoKeys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckVoteYesKeys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckVoteYesKeys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckVoteYesKeys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckHorizontalAim
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckHorizontalAim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckHorizontalAim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckVerticalAim
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckVerticalAim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckVerticalAim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckTabKeys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckTabKeys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckTabKeys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckEscapeKeys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckEscapeKeys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckEscapeKeys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.ResetKeyBinds
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::ResetKeyBinds()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "ResetKeyBinds");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckPushToTalkKeys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckPushToTalkKeys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckPushToTalkKeys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckAllChatKeys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckAllChatKeys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckAllChatKeys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckTeamChatKeys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckTeamChatKeys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckTeamChatKeys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckQuickChat4Keys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckQuickChat4Keys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckQuickChat4Keys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckQuickChat3Keys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckQuickChat3Keys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckQuickChat3Keys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckQuickChat2Keys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckQuickChat2Keys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckQuickChat2Keys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckQuickChat1Keys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckQuickChat1Keys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckQuickChat1Keys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckEmoteKeys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckEmoteKeys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckEmoteKeys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckSpawnBallKeys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckSpawnBallKeys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckSpawnBallKeys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckToggleCameraKeys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckToggleCameraKeys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckToggleCameraKeys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckGkButtonKeys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckGkButtonKeys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckGkButtonKeys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckSlideTackleKeys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckSlideTackleKeys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckSlideTackleKeys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckJuggleKeys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckJuggleKeys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckJuggleKeys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckDribbleKeys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckDribbleKeys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckDribbleKeys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckKickKeys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckKickKeys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckKickKeys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckJumpKeys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckJumpKeys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckJumpKeys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckSprintKeys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckSprintKeys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckSprintKeys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckHorizontalMovementKeys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckHorizontalMovementKeys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckHorizontalMovementKeys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckVerticalMovementKeys
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckVerticalMovementKeys()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckVerticalMovementKeys");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckKeybinds
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::CheckKeybinds()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckKeybinds");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Apply_FoliageQuality
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::Apply_FoliageQuality()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Apply_FoliageQuality");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Update_SettingsListItems
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::Update_SettingsListItems()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Update_SettingsListItems");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Save_Settings-Online
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Param_PreferredRegion                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int32                                   Param_TextChatMode                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Param_ProfanityFilter                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// TArray<class FString>                   MutePlayers                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UPSO_GameInstance_C::Save_SettingsMinusOnline(const class FString& Param_PreferredRegion, int32 Param_TextChatMode, bool Param_ProfanityFilter, const TArray<class FString>& MutePlayers)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Save_Settings-Online");

	Params::PSO_GameInstance_C_Save_SettingsMinusOnline Parms{};

	Parms.Param_PreferredRegion = std::move(Param_PreferredRegion);
	Parms.Param_TextChatMode = Param_TextChatMode;
	Parms.Param_ProfanityFilter = Param_ProfanityFilter;
	Parms.MutePlayers = std::move(MutePlayers);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Save_Settings-Camera
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Param_OnestPersonFOV                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Param_ThreerdPersonFOV                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Param_ThreerdPersonDistance                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Param_ThreerdPersonHeight                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Param_BallIndicatorSize                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Param_GkNetTransparency                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::Save_SettingsMinusCamera(float Param_OnestPersonFOV, float Param_ThreerdPersonFOV, float Param_ThreerdPersonDistance, float Param_ThreerdPersonHeight, int32 Param_BallIndicatorSize, float Param_GkNetTransparency)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Save_Settings-Camera");

	Params::PSO_GameInstance_C_Save_SettingsMinusCamera Parms{};

	Parms.Param_OnestPersonFOV = Param_OnestPersonFOV;
	Parms.Param_ThreerdPersonFOV = Param_ThreerdPersonFOV;
	Parms.Param_ThreerdPersonDistance = Param_ThreerdPersonDistance;
	Parms.Param_ThreerdPersonHeight = Param_ThreerdPersonHeight;
	Parms.Param_BallIndicatorSize = Param_BallIndicatorSize;
	Parms.Param_GkNetTransparency = Param_GkNetTransparency;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Save_Settings-Video
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Param_DisplayType                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Param_FullscreenResolution                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Param_RenderResolution                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Param_FPS_Limit                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Param_TextureQuality                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Param_ShadowQuality                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Param_FoliageQuality                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Param_EffectsQuality                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Param_AntiAliasingQuality                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Param_PostProcessingQuality                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Param_ViewDistance                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::Save_SettingsMinusVideo(int32 Param_DisplayType, int32 Param_FullscreenResolution, float Param_RenderResolution, int32 Param_FPS_Limit, int32 Param_TextureQuality, int32 Param_ShadowQuality, int32 Param_FoliageQuality, int32 Param_EffectsQuality, int32 Param_AntiAliasingQuality, int32 Param_PostProcessingQuality, int32 Param_ViewDistance)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Save_Settings-Video");

	Params::PSO_GameInstance_C_Save_SettingsMinusVideo Parms{};

	Parms.Param_DisplayType = Param_DisplayType;
	Parms.Param_FullscreenResolution = Param_FullscreenResolution;
	Parms.Param_RenderResolution = Param_RenderResolution;
	Parms.Param_FPS_Limit = Param_FPS_Limit;
	Parms.Param_TextureQuality = Param_TextureQuality;
	Parms.Param_ShadowQuality = Param_ShadowQuality;
	Parms.Param_FoliageQuality = Param_FoliageQuality;
	Parms.Param_EffectsQuality = Param_EffectsQuality;
	Parms.Param_AntiAliasingQuality = Param_AntiAliasingQuality;
	Parms.Param_PostProcessingQuality = Param_PostProcessingQuality;
	Parms.Param_ViewDistance = Param_ViewDistance;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Save_Settings-Audio
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Param_SoundEffectsVolume                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Param_AmbientVolume                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Param_MusicVolume                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Param_VoiceChatVolume                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::Save_SettingsMinusAudio(float Param_SoundEffectsVolume, float Param_AmbientVolume, float Param_MusicVolume, float Param_VoiceChatVolume)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Save_Settings-Audio");

	Params::PSO_GameInstance_C_Save_SettingsMinusAudio Parms{};

	Parms.Param_SoundEffectsVolume = Param_SoundEffectsVolume;
	Parms.Param_AmbientVolume = Param_AmbientVolume;
	Parms.Param_MusicVolume = Param_MusicVolume;
	Parms.Param_VoiceChatVolume = Param_VoiceChatVolume;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Save_Settings-Controls
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Param_LookSensitivity                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Param_HeightSensitivity                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Param_CurveSensitivity                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Param_InvertYLook                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    Param_InvertXLook                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    Param_ToggleGkCatch                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// int32                                   Param_GkDiveButton                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::Save_SettingsMinusControls(float Param_LookSensitivity, float Param_HeightSensitivity, float Param_CurveSensitivity, bool Param_InvertYLook, bool Param_InvertXLook, bool Param_ToggleGkCatch, int32 Param_GkDiveButton)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Save_Settings-Controls");

	Params::PSO_GameInstance_C_Save_SettingsMinusControls Parms{};

	Parms.Param_LookSensitivity = Param_LookSensitivity;
	Parms.Param_HeightSensitivity = Param_HeightSensitivity;
	Parms.Param_CurveSensitivity = Param_CurveSensitivity;
	Parms.Param_InvertYLook = Param_InvertYLook;
	Parms.Param_InvertXLook = Param_InvertXLook;
	Parms.Param_ToggleGkCatch = Param_ToggleGkCatch;
	Parms.Param_GkDiveButton = Param_GkDiveButton;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Load_Settings
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::Load_Settings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Load_Settings");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.UpdateOnlineSettings
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::UpdateOnlineSettings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "UpdateOnlineSettings");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Load_Settings-Online
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::Load_SettingsMinusOnline()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Load_Settings-Online");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.UpdateCameraSettings
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::UpdateCameraSettings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "UpdateCameraSettings");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Load_Settings-Camera
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::Load_SettingsMinusCamera()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Load_Settings-Camera");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Load_Settings-Video
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::Load_SettingsMinusVideo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Load_Settings-Video");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.UpdateControlSettings
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::UpdateControlSettings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "UpdateControlSettings");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Load_Settings-Audio
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::Load_SettingsMinusAudio()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Load_Settings-Audio");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Load_Settings-Controls
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::Load_SettingsMinusControls()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Load_Settings-Controls");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Borderless
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::Borderless()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Borderless");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Apply_FullscreenResolution
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::Apply_FullscreenResolution()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Apply_FullscreenResolution");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.UpdateAudioSettings
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::UpdateAudioSettings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "UpdateAudioSettings");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Apply_FPS_Limit
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::Apply_FPS_Limit()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Apply_FPS_Limit");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Apply_PostProcessingQuality
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::Apply_PostProcessingQuality()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Apply_PostProcessingQuality");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Apply_AntiAliasingQuality
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::Apply_AntiAliasingQuality()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Apply_AntiAliasingQuality");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Apply_EffectsQuality
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::Apply_EffectsQuality()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Apply_EffectsQuality");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Apply_ShadowQuality
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::Apply_ShadowQuality()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Apply_ShadowQuality");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Apply_ViewDistance
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::Apply_ViewDistance()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Apply_ViewDistance");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Apply_TextureQuality
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::Apply_TextureQuality()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Apply_TextureQuality");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Apply_RenderResolution
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::Apply_RenderResolution()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Apply_RenderResolution");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.Apply_DisplayType
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::Apply_DisplayType()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "Apply_DisplayType");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.GameliftServer_SetHostID
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Param_HostId                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::GameliftServer_SetHostID(const class FString& Param_HostId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "GameliftServer_SetHostID");

	Params::PSO_GameInstance_C_GameliftServer_SetHostID Parms{};

	Parms.Param_HostId = std::move(Param_HostId);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.GameliftServer_EC2Initialize
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ADS_EntryGameMode_C*              DS_Entry_GameMode                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::GameliftServer_EC2Initialize(class ADS_EntryGameMode_C* DS_Entry_GameMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "GameliftServer_EC2Initialize");

	Params::PSO_GameInstance_C_GameliftServer_EC2Initialize Parms{};

	Parms.DS_Entry_GameMode = DS_Entry_GameMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.GameliftServer_SetMaxPlayers
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Param_MaxPlayers                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::GameliftServer_SetMaxPlayers(int32 Param_MaxPlayers)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "GameliftServer_SetMaxPlayers");

	Params::PSO_GameInstance_C_GameliftServer_SetMaxPlayers Parms{};

	Parms.Param_MaxPlayers = Param_MaxPlayers;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.GameliftServer_SetSessionName
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           SessionName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::GameliftServer_SetSessionName(const class FString& SessionName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "GameliftServer_SetSessionName");

	Params::PSO_GameInstance_C_GameliftServer_SetSessionName Parms{};

	Parms.SessionName = std::move(SessionName);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.GameliftServer_SetGameSessionID
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Param_GameSessionID                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::GameliftServer_SetGameSessionID(const class FString& Param_GameSessionID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "GameliftServer_SetGameSessionID");

	Params::PSO_GameInstance_C_GameliftServer_SetGameSessionID Parms{};

	Parms.Param_GameSessionID = std::move(Param_GameSessionID);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.GameliftServer_SetGameMode
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           GameMode                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::GameliftServer_SetGameMode(const class FString& GameMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "GameliftServer_SetGameMode");

	Params::PSO_GameInstance_C_GameliftServer_SetGameMode Parms{};

	Parms.GameMode = std::move(GameMode);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.GameliftServer_Shutdown
// (BlueprintCallable, BlueprintEvent)

void UPSO_GameInstance_C::GameliftServer_Shutdown()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "GameliftServer_Shutdown");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PSO_GameInstance.PSO_GameInstance_C.GameliftServer_Initialize
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class ADS_EntryGameMode_C*              DS_EntryGameMode                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::GameliftServer_Initialize(class ADS_EntryGameMode_C* DS_EntryGameMode)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "GameliftServer_Initialize");

	Params::PSO_GameInstance_C_GameliftServer_Initialize Parms{};

	Parms.DS_EntryGameMode = DS_EntryGameMode;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.OnCallback_E3B6E41E4CD5C53640E4A085DB144151
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FEncryptedAppTicketResponse      Data                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
// bool                                    bWasSuccessful                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UPSO_GameInstance_C::OnCallback_E3B6E41E4CD5C53640E4A085DB144151(const struct FEncryptedAppTicketResponse& Data, bool bWasSuccessful)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "OnCallback_E3B6E41E4CD5C53640E4A085DB144151");

	Params::PSO_GameInstance_C_OnCallback_E3B6E41E4CD5C53640E4A085DB144151 Parms{};

	Parms.Data = std::move(Data);
	Parms.bWasSuccessful = bWasSuccessful;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PSO_GameInstance.PSO_GameInstance_C.CalculatePlayerLevel
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   PlayersTotalXP                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Param_PlayerLevel                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Param_LevelCompleted_                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::CalculatePlayerLevel(int32 PlayersTotalXP, int32* Param_PlayerLevel, float* Param_LevelCompleted_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CalculatePlayerLevel");

	Params::PSO_GameInstance_C_CalculatePlayerLevel Parms{};

	Parms.PlayersTotalXP = PlayersTotalXP;

	UObject::ProcessEvent(Func, &Parms);

	if (Param_PlayerLevel != nullptr)
		*Param_PlayerLevel = Parms.Param_PlayerLevel;

	if (Param_LevelCompleted_ != nullptr)
		*Param_LevelCompleted_ = Parms.Param_LevelCompleted_;
}


// Function PSO_GameInstance.PSO_GameInstance_C.CalculateXPToNextLevel
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Level                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Param_NextLevelXP                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Param_PreviousLevelXP                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::CalculateXPToNextLevel(int32 Level, int32* Param_NextLevelXP, int32* Param_PreviousLevelXP)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CalculateXPToNextLevel");

	Params::PSO_GameInstance_C_CalculateXPToNextLevel Parms{};

	Parms.Level = Level;

	UObject::ProcessEvent(Func, &Parms);

	if (Param_NextLevelXP != nullptr)
		*Param_NextLevelXP = Parms.Param_NextLevelXP;

	if (Param_PreviousLevelXP != nullptr)
		*Param_PreviousLevelXP = Parms.Param_PreviousLevelXP;
}


// Function PSO_GameInstance.PSO_GameInstance_C.CheckStringProfanity
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           InputMessage                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class FString                           OutputMessage                                          (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void UPSO_GameInstance_C::CheckStringProfanity(const class FString& InputMessage, class FString* OutputMessage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PSO_GameInstance_C", "CheckStringProfanity");

	Params::PSO_GameInstance_C_CheckStringProfanity Parms{};

	Parms.InputMessage = std::move(InputMessage);

	UObject::ProcessEvent(Func, &Parms);

	if (OutputMessage != nullptr)
		*OutputMessage = std::move(Parms.OutputMessage);
}

}

