#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PSO_SettingsMinusAudio

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PSO_Settings-Audio.PSO_Settings-Audio_C
// 0x0010 (0x0038 - 0x0028)
class UPSO_SettingsMinusAudio_C final : public USaveGame
{
public:
	float                                         SFX_Volume;                                        // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Ambient_Volume;                                    // 0x002C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Music_Volume;                                      // 0x0030(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         VoiceChat_Volume;                                  // 0x0034(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PSO_Settings-Audio_C">();
	}
	static class UPSO_SettingsMinusAudio_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPSO_SettingsMinusAudio_C>();
	}
};

}

