#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Settings

#include "Basic.hpp"

#include "Settings_classes.hpp"
#include "Settings_parameters.hpp"


namespace SDK
{

// Function Settings.Settings_C.ExecuteUbergraph_Settings
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USettings_C::ExecuteUbergraph_Settings(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Settings_C", "ExecuteUbergraph_Settings");

	Params::Settings_C_ExecuteUbergraph_Settings Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Settings.Settings_C.BndEvt__Settings_ApplyFullscreenButton_K2Node_ComponentBoundEvent_17_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void USettings_C::BndEvt__Settings_ApplyFullscreenButton_K2Node_ComponentBoundEvent_17_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Settings_C", "BndEvt__Settings_ApplyFullscreenButton_K2Node_ComponentBoundEvent_17_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Settings.Settings_C.BndEvt__Settings_ApplyFullscreenButton_K2Node_ComponentBoundEvent_16_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void USettings_C::BndEvt__Settings_ApplyFullscreenButton_K2Node_ComponentBoundEvent_16_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Settings_C", "BndEvt__Settings_ApplyFullscreenButton_K2Node_ComponentBoundEvent_16_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Settings.Settings_C.BndEvt__Settings_ResetKeyBindsButton_K2Node_ComponentBoundEvent_9_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void USettings_C::BndEvt__Settings_ResetKeyBindsButton_K2Node_ComponentBoundEvent_9_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Settings_C", "BndEvt__Settings_ResetKeyBindsButton_K2Node_ComponentBoundEvent_9_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Settings.Settings_C.BndEvt__Settings_ResetKeyBindsButton_K2Node_ComponentBoundEvent_8_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void USettings_C::BndEvt__Settings_ResetKeyBindsButton_K2Node_ComponentBoundEvent_8_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Settings_C", "BndEvt__Settings_ResetKeyBindsButton_K2Node_ComponentBoundEvent_8_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Settings.Settings_C.BndEvt__Settings_ResetKeybindsNo_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void USettings_C::BndEvt__Settings_ResetKeybindsNo_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Settings_C", "BndEvt__Settings_ResetKeybindsNo_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Settings.Settings_C.BndEvt__Settings_ResetKeybindsYes_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void USettings_C::BndEvt__Settings_ResetKeybindsYes_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Settings_C", "BndEvt__Settings_ResetKeybindsYes_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Settings.Settings_C.BndEvt__Settings_ResetKeyBinds_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void USettings_C::BndEvt__Settings_ResetKeyBinds_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Settings_C", "BndEvt__Settings_ResetKeyBinds_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Settings.Settings_C.BndEvt__Settings_ApplyFullscreenButton_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void USettings_C::BndEvt__Settings_ApplyFullscreenButton_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Settings_C", "BndEvt__Settings_ApplyFullscreenButton_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Settings.Settings_C.UpdateItemsList
// (BlueprintCallable, BlueprintEvent)

void USettings_C::UpdateItemsList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Settings_C", "UpdateItemsList");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Settings.Settings_C.BndEvt__Settings_Camera_1_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void USettings_C::BndEvt__Settings_Camera_1_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Settings_C", "BndEvt__Settings_Camera_1_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Settings.Settings_C.Disable
// (BlueprintCallable, BlueprintEvent)

void USettings_C::Disable()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Settings_C", "Disable");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Settings.Settings_C.BndEvt__Camera_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void USettings_C::BndEvt__Camera_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Settings_C", "BndEvt__Camera_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Settings.Settings_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void USettings_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Settings_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Settings.Settings_C.BndEvt__Video_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void USettings_C::BndEvt__Video_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Settings_C", "BndEvt__Video_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Settings.Settings_C.BndEvt__Audio_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void USettings_C::BndEvt__Audio_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Settings_C", "BndEvt__Audio_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Settings.Settings_C.BndEvt__Controls_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void USettings_C::BndEvt__Controls_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Settings_C", "BndEvt__Controls_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Settings.Settings_C.BndEvt__Back_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void USettings_C::BndEvt__Back_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Settings_C", "BndEvt__Back_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Settings.Settings_C.Enable
// (BlueprintCallable, BlueprintEvent)

void USettings_C::Enable()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Settings_C", "Enable");

	UObject::ProcessEvent(Func, nullptr);
}

}

