#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SP_Kickbar

#include "Basic.hpp"

#include "SP_Kickbar_classes.hpp"
#include "SP_Kickbar_parameters.hpp"


namespace SDK
{

// Function SP_Kickbar.SP_KickBar_C.ExecuteUbergraph_SP_KickBar
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USP_KickBar_C::ExecuteUbergraph_SP_KickBar(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SP_KickBar_C", "ExecuteUbergraph_SP_KickBar");

	Params::SP_KickBar_C_ExecuteUbergraph_SP_KickBar Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SP_Kickbar.SP_KickBar_C.StartUpdateLoop
// (BlueprintCallable, BlueprintEvent)

void USP_KickBar_C::StartUpdateLoop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SP_KickBar_C", "StartUpdateLoop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SP_Kickbar.SP_KickBar_C.UpdateLoop
// (BlueprintCallable, BlueprintEvent)

void USP_KickBar_C::UpdateLoop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SP_KickBar_C", "UpdateLoop");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SP_Kickbar.SP_KickBar_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void USP_KickBar_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SP_KickBar_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SP_Kickbar.SP_KickBar_C.Get_KickPower
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float USP_KickBar_C::Get_KickPower()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SP_KickBar_C", "Get_KickPower");

	Params::SP_KickBar_C_Get_KickPower Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SP_Kickbar.SP_KickBar_C.Get_KickBarColor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FLinearColor                     ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

struct FLinearColor USP_KickBar_C::Get_KickBarColor()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SP_KickBar_C", "Get_KickBarColor");

	Params::SP_KickBar_C_Get_KickBarColor Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SP_Kickbar.SP_KickBar_C.Get_Stamina
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float USP_KickBar_C::Get_Stamina()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SP_KickBar_C", "Get_Stamina");

	Params::SP_KickBar_C_Get_Stamina Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SP_Kickbar.SP_KickBar_C.Get_GkGlovesImage
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush USP_KickBar_C::Get_GkGlovesImage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SP_KickBar_C", "Get_GkGlovesImage");

	Params::SP_KickBar_C_Get_GkGlovesImage Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SP_Kickbar.SP_KickBar_C.Get_YellowCardVis
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility USP_KickBar_C::Get_YellowCardVis()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SP_KickBar_C", "Get_YellowCardVis");

	Params::SP_KickBar_C_Get_YellowCardVis Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

