#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SP_ShirtData

#include "Basic.hpp"

#include "SP_ShirtData_classes.hpp"
#include "SP_ShirtData_parameters.hpp"


namespace SDK
{

// Function SP_ShirtData.SP_ShirtData_C.ExecuteUbergraph_SP_ShirtData
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USP_ShirtData_C::ExecuteUbergraph_SP_ShirtData(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SP_ShirtData_C", "ExecuteUbergraph_SP_ShirtData");

	Params::SP_ShirtData_C_ExecuteUbergraph_SP_ShirtData Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SP_ShirtData.SP_ShirtData_C.RecieveShirtData
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             PlayerName                                             (BlueprintVisible, BlueprintReadOnly, Parm)
// class FText                             PlayerNumber                                           (BlueprintVisible, BlueprintReadOnly, Parm)
// int32                                   FontType                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FSlateColor                      FontColor                                              (BlueprintVisible, BlueprintReadOnly, Parm)
// int32                                   FrontNumber                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USP_ShirtData_C::RecieveShirtData(const class FText& PlayerName, const class FText& PlayerNumber, int32 FontType, const struct FSlateColor& FontColor, int32 FrontNumber)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SP_ShirtData_C", "RecieveShirtData");

	Params::SP_ShirtData_C_RecieveShirtData Parms{};

	Parms.PlayerName = std::move(PlayerName);
	Parms.PlayerNumber = std::move(PlayerNumber);
	Parms.FontType = FontType;
	Parms.FontColor = std::move(FontColor);
	Parms.FrontNumber = FrontNumber;

	UObject::ProcessEvent(Func, &Parms);
}

}

