#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TeamCustomization

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "UMG_classes.hpp"
#include "CustomTeam_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass TeamCustomization.TeamCustomization_C
// 0x0930 (0x0B90 - 0x0260)
class UTeamCustomization_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0260(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       FadeIn;                                            // 0x0268(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UButton*                                AltGK;                                             // 0x0270(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                AltKit;                                            // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                AwayGK;                                            // 0x0280(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                AwayKit;                                           // 0x0288(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Back;                                              // 0x0290(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Cancel;                                            // 0x0298(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           Canvas;                                            // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ExitBG;                                            // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ExitCancel;                                        // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ExitNo;                                            // 0x02B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ExitPanelBG;                                       // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           ExitScreen;                                        // 0x02C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             ExitTextNo;                                        // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             ExitTextNo_1;                                      // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             ExitTextYes;                                       // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ExitYes;                                           // 0x02E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 FadeBG;                                            // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                HomeGK;                                            // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                HomeKit;                                           // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 PanelBG;                                           // 0x0308(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        PanelSwitcher;                                     // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ResetAppearance;                                   // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ResetAppearance_1;                                 // 0x0320(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                RotateLeft;                                        // 0x0328(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                RotateRight;                                       // 0x0330(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                Save;                                              // 0x0338(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UColorWidget*                           ShirtColor1;                                       // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtColor1Copy;                                   // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtColor1Paste;                                  // 0x0350(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USlider*                                ShirtColor1Slider;                                 // 0x0358(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UColorWidget*                           ShirtColor2;                                       // 0x0360(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtColor2Copy;                                   // 0x0368(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtColor2Paste;                                  // 0x0370(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USlider*                                ShirtColor2Slider;                                 // 0x0378(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UColorWidget*                           ShirtFontColor;                                    // 0x0380(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtFontColorCopy;                                // 0x0388(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtFontColorPaste;                               // 0x0390(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USlider*                                ShirtFontColorSlider;                              // 0x0398(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UComboBoxString*                        ShirtFontStyle;                                    // 0x03A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern;                                      // 0x03A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_1;                                    // 0x03B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_2;                                    // 0x03B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_3;                                    // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_4;                                    // 0x03C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_5;                                    // 0x03D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_6;                                    // 0x03D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_7;                                    // 0x03E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_8;                                    // 0x03E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_9;                                    // 0x03F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_10;                                   // 0x03F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_11;                                   // 0x0400(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_12;                                   // 0x0408(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_13;                                   // 0x0410(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_14;                                   // 0x0418(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_15;                                   // 0x0420(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_16;                                   // 0x0428(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_17;                                   // 0x0430(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_18;                                   // 0x0438(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_19;                                   // 0x0440(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_20;                                   // 0x0448(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_21;                                   // 0x0450(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_22;                                   // 0x0458(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_23;                                   // 0x0460(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_24;                                   // 0x0468(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_25;                                   // 0x0470(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_26;                                   // 0x0478(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_27;                                   // 0x0480(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_28;                                   // 0x0488(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_29;                                   // 0x0490(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_30;                                   // 0x0498(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_31;                                   // 0x04A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_32;                                   // 0x04A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_33;                                   // 0x04B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_34;                                   // 0x04B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_35;                                   // 0x04C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_36;                                   // 0x04C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_37;                                   // 0x04D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_38;                                   // 0x04D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_39;                                   // 0x04E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_40;                                   // 0x04E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_41;                                   // 0x04F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_42;                                   // 0x04F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_43;                                   // 0x0500(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPattern_44;                                   // 0x0508(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShirtPatternButton;                                // 0x0510(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UComboBoxString*                        ShortFrontNumber;                                  // 0x0518(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UColorWidget*                           ShortsColor1;                                      // 0x0520(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsColor1Copy;                                  // 0x0528(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsColor1Paste;                                 // 0x0530(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USlider*                                ShortsColor1Slider;                                // 0x0538(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UColorWidget*                           ShortsColor2;                                      // 0x0540(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsColor2Copy;                                  // 0x0548(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsColor2Paste;                                 // 0x0550(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USlider*                                ShortsColor2Slider;                                // 0x0558(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsPattern;                                     // 0x0560(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsPattern_1;                                   // 0x0568(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsPattern_2;                                   // 0x0570(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsPattern_3;                                   // 0x0578(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsPattern_4;                                   // 0x0580(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsPattern_5;                                   // 0x0588(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsPattern_6;                                   // 0x0590(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsPattern_7;                                   // 0x0598(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsPattern_8;                                   // 0x05A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsPattern_9;                                   // 0x05A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsPattern_10;                                  // 0x05B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsPattern_11;                                  // 0x05B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsPattern_12;                                  // 0x05C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsPattern_13;                                  // 0x05C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsPattern_14;                                  // 0x05D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsPattern_15;                                  // 0x05D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsPattern_16;                                  // 0x05E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsPattern_17;                                  // 0x05E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                ShortsPatternButton;                               // 0x05F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UColorWidget*                           SocksColor1;                                       // 0x05F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SocksColor1Copy;                                   // 0x0600(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SocksColor1Paste;                                  // 0x0608(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USlider*                                SocksColor1Slider;                                 // 0x0610(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UColorWidget*                           SocksColor2;                                       // 0x0618(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SocksColor2Copy;                                   // 0x0620(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SocksColor2Paste;                                  // 0x0628(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USlider*                                SocksColor2Slider;                                 // 0x0630(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SocksPattern;                                      // 0x0638(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SocksPattern_1;                                    // 0x0640(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SocksPattern_2;                                    // 0x0648(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SocksPattern_3;                                    // 0x0650(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SocksPattern_4;                                    // 0x0658(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SocksPattern_5;                                    // 0x0660(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SocksPattern_6;                                    // 0x0668(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SocksPattern_7;                                    // 0x0670(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SocksPattern_8;                                    // 0x0678(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SocksPattern_9;                                    // 0x0680(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SocksPattern_10;                                   // 0x0688(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SocksPattern_11;                                   // 0x0690(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SocksPattern_12;                                   // 0x0698(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SocksPattern_13;                                   // 0x06A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SocksPattern_14;                                   // 0x06A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SocksPattern_15;                                   // 0x06B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SocksPattern_16;                                   // 0x06B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                SocksPatternButton;                                // 0x06C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        SubTabButtons;                                     // 0x06C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TabUnderliner;                                     // 0x06D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TabUnderliner_1;                                   // 0x06D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TabUnderliner_2;                                   // 0x06E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TabUnderliner_3;                                   // 0x06E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TabUnderliner_4;                                   // 0x06F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TabUnderliner_5;                                   // 0x06F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TabUnderliner_6;                                   // 0x0700(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TabUnderliner_7;                                   // 0x0708(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TabUnderliner_8;                                   // 0x0710(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TabUnderliner_9;                                   // 0x0718(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableTextBox*                       TeamAbbreviation;                                  // 0x0720(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                TeamInfo;                                          // 0x0728(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                TeamInfoSubTabButton;                              // 0x0730(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableTextBox*                       TeamName;                                          // 0x0738(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock;                                         // 0x0740(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_1;                                       // 0x0748(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_2;                                       // 0x0750(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMainMenu_C*                            MainMenu;                                          // 0x0758(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPSO_GameInstance_C*                    PSO_GameInstance;                                  // 0x0760(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AMM_Character_C*                        MM_Character;                                      // 0x0768(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         KitIndex;                                          // 0x0770(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_267E[0x4];                                     // 0x0774(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FCustomTeam                            CustomTeam;                                        // 0x0778(0x03F0)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	int32                                         ShirtPatternIndex;                                 // 0x0B68(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ShortsPatternIndex;                                // 0x0B6C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         SocksPatternIndex;                                 // 0x0B70(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ShirtFrontNumberIndex;                             // 0x0B74(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CopiedColor;                                       // 0x0B78(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CopiedSlider;                                      // 0x0B88(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_TeamCustomization(int32 EntryPoint);
	void BndEvt__TeamCustomization_ShortsPattern_17_K2Node_ComponentBoundEvent_116_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_SocksPattern_16_K2Node_ComponentBoundEvent_132_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_SocksPattern_15_K2Node_ComponentBoundEvent_131_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_SocksPattern_14_K2Node_ComponentBoundEvent_130_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_SocksPattern_13_K2Node_ComponentBoundEvent_129_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_SocksPattern_12_K2Node_ComponentBoundEvent_125_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_SocksPattern_11_K2Node_ComponentBoundEvent_124_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_SocksPattern_10_K2Node_ComponentBoundEvent_123_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_SocksPattern_9_K2Node_ComponentBoundEvent_122_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_SocksPattern_8_K2Node_ComponentBoundEvent_121_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_SocksPattern_7_K2Node_ComponentBoundEvent_120_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_SocksPattern_6_K2Node_ComponentBoundEvent_119_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_SocksPattern_5_K2Node_ComponentBoundEvent_118_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_SocksPattern_4_K2Node_ComponentBoundEvent_117_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShortsPattern_16_K2Node_ComponentBoundEvent_115_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShortsPattern_15_K2Node_ComponentBoundEvent_114_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShortsPattern_14_K2Node_ComponentBoundEvent_113_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShortsPattern_13_K2Node_ComponentBoundEvent_112_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShortsPattern_12_K2Node_ComponentBoundEvent_111_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShortsPattern_11_K2Node_ComponentBoundEvent_110_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShortsPattern_10_K2Node_ComponentBoundEvent_109_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShortsPattern_9_K2Node_ComponentBoundEvent_108_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShortsPattern_8_K2Node_ComponentBoundEvent_107_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShortsPattern_7_K2Node_ComponentBoundEvent_106_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShortsPattern_6_K2Node_ComponentBoundEvent_105_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShortsPattern_5_K2Node_ComponentBoundEvent_104_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShortsPattern_4_K2Node_ComponentBoundEvent_103_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_44_K2Node_ComponentBoundEvent_102_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_43_K2Node_ComponentBoundEvent_101_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_42_K2Node_ComponentBoundEvent_100_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_41_K2Node_ComponentBoundEvent_99_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_40_K2Node_ComponentBoundEvent_98_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_39_K2Node_ComponentBoundEvent_97_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_38_K2Node_ComponentBoundEvent_96_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_37_K2Node_ComponentBoundEvent_95_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_36_K2Node_ComponentBoundEvent_94_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_35_K2Node_ComponentBoundEvent_93_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_34_K2Node_ComponentBoundEvent_92_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_33_K2Node_ComponentBoundEvent_91_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_32_K2Node_ComponentBoundEvent_90_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_31_K2Node_ComponentBoundEvent_88_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_30_K2Node_ComponentBoundEvent_87_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_29_K2Node_ComponentBoundEvent_86_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_28_K2Node_ComponentBoundEvent_85_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_27_K2Node_ComponentBoundEvent_84_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_26_K2Node_ComponentBoundEvent_83_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_25_K2Node_ComponentBoundEvent_82_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_24_K2Node_ComponentBoundEvent_81_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_23_K2Node_ComponentBoundEvent_80_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_22_K2Node_ComponentBoundEvent_79_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_21_K2Node_ComponentBoundEvent_78_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_20_K2Node_ComponentBoundEvent_77_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_19_K2Node_ComponentBoundEvent_76_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_18_K2Node_ComponentBoundEvent_75_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_17_K2Node_ComponentBoundEvent_74_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_16_K2Node_ComponentBoundEvent_73_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_15_K2Node_ComponentBoundEvent_72_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_14_K2Node_ComponentBoundEvent_71_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__PlayerCustomization_RotateLeft_K2Node_ComponentBoundEvent_128_OnButtonReleasedEvent__DelegateSignature();
	void BndEvt__PlayerCustomization_RotateLeft_K2Node_ComponentBoundEvent_127_OnButtonPressedEvent__DelegateSignature();
	void BndEvt__PlayerCustomization_RotateRight_K2Node_ComponentBoundEvent_126_OnButtonReleasedEvent__DelegateSignature();
	void BndEvt__PlayerCustomization_RotateRight_K2Node_ComponentBoundEvent_89_OnButtonPressedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_13_K2Node_ComponentBoundEvent_70_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_12_K2Node_ComponentBoundEvent_69_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_11_K2Node_ComponentBoundEvent_68_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_10_K2Node_ComponentBoundEvent_67_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_9_K2Node_ComponentBoundEvent_66_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_8_K2Node_ComponentBoundEvent_65_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_7_K2Node_ComponentBoundEvent_64_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_6_K2Node_ComponentBoundEvent_32_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_5_K2Node_ComponentBoundEvent_24_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ExitCancel_K2Node_ComponentBoundEvent_63_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ExitNo_K2Node_ComponentBoundEvent_62_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ExitYes_K2Node_ComponentBoundEvent_60_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_TeamAbbreviation_K2Node_ComponentBoundEvent_58_OnEditableTextBoxCommittedEvent__DelegateSignature(const class FText& Text, ETextCommit CommitMethod);
	void BndEvt__TeamCustomization_TeamName_K2Node_ComponentBoundEvent_51_OnEditableTextBoxCommittedEvent__DelegateSignature(const class FText& Text, ETextCommit CommitMethod);
	void BndEvt__TeamCustomization_TeamAbbreviation_K2Node_ComponentBoundEvent_50_OnEditableTextBoxChangedEvent__DelegateSignature(const class FText& Text);
	void BndEvt__TeamCustomization_TeamName_K2Node_ComponentBoundEvent_49_OnEditableTextBoxChangedEvent__DelegateSignature(const class FText& Text);
	void BndEvt__TeamCustomization_SocksColor2Paste_K2Node_ComponentBoundEvent_48_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_SocksColor2Copy_K2Node_ComponentBoundEvent_47_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_SocksColor1Paste_K2Node_ComponentBoundEvent_46_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_SocksColor1Copy_K2Node_ComponentBoundEvent_45_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShortsColor2Paste_K2Node_ComponentBoundEvent_44_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShortsColor2Copy_K2Node_ComponentBoundEvent_43_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShortsColor1Paste_K2Node_ComponentBoundEvent_42_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShortsColor1Copy_K2Node_ComponentBoundEvent_41_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtFontColorPaste_K2Node_ComponentBoundEvent_40_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtColor2Paste_K2Node_ComponentBoundEvent_39_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtColor1Paste_K2Node_ComponentBoundEvent_38_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtFontColorCopy_K2Node_ComponentBoundEvent_37_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtColor2Copy_K2Node_ComponentBoundEvent_36_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtColor1Copy_K2Node_ComponentBoundEvent_35_OnButtonClickedEvent__DelegateSignature();
	void UpdateShirtFontColor(const struct FLinearColor& InputPin);
	void BndEvt__TeamCustomization_ShirtFontColorSlider_K2Node_ComponentBoundEvent_34_OnFloatValueChangedEvent__DelegateSignature(float Value);
	void BndEvt__TeamCustomization_ShirtFontColor_K2Node_ComponentBoundEvent_33_ColorChangedEvent__DelegateSignature(const struct FLinearColor& NewColor);
	void BndEvt__TeamCustomization_Cancel_K2Node_ComponentBoundEvent_21_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_Save_K2Node_ComponentBoundEvent_20_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__MM_PlayerCustomizationNew_AppearanceButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShortFrontNumber_K2Node_ComponentBoundEvent_19_OnSelectionChangedEvent__DelegateSignature(const class FString& SelectedItem, ESelectInfo SelectionType);
	void BndEvt__TeamCustomization_SocksColor2Slider_K2Node_ComponentBoundEvent_61_OnFloatValueChangedEvent__DelegateSignature(float Value);
	void BndEvt__TeamCustomization_SocksColor2_K2Node_ComponentBoundEvent_59_ColorChangedEvent__DelegateSignature(const struct FLinearColor& NewColor);
	void BndEvt__TeamCustomization_SocksColor1Slider_K2Node_ComponentBoundEvent_57_OnFloatValueChangedEvent__DelegateSignature(float Value);
	void BndEvt__TeamCustomization_SocksColor1_K2Node_ComponentBoundEvent_56_ColorChangedEvent__DelegateSignature(const struct FLinearColor& NewColor);
	void BndEvt__TeamCustomization_SocksPattern_3_K2Node_ComponentBoundEvent_55_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_SocksPattern_2_K2Node_ComponentBoundEvent_54_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_SocksPattern_1_K2Node_ComponentBoundEvent_53_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_SocksPattern_K2Node_ComponentBoundEvent_52_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__MM_PlayerCustomizationNew_HairButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature();
	void UpdateSocksColor2(const struct FLinearColor& InputPin);
	void UpdateSocksColor1(const struct FLinearColor& InputPin);
	void BndEvt__MM_PlayerCustomizationNew_ClothingButton_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__MM_PlayerCustomizationNew_ShoesButton_K2Node_ComponentBoundEvent_3_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__MM_PlayerCustomizationNew_AccessoriesButon_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__MM_PlayerCustomizationNew_SkinColorButton_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature();
	void UpdateShortsColor2(const struct FLinearColor& InputPin);
	void UpdateShirtColor2(const struct FLinearColor& InputPin);
	void UpdateShortsColor1(const struct FLinearColor& InputPin);
	void UpdateShirtColor1(const struct FLinearColor& InputPin);
	void BndEvt__TeamCustomization_ShortsColor2Slider_K2Node_ComponentBoundEvent_40_OnFloatValueChangedEvent__DelegateSignature(float Value);
	void BndEvt__TeamCustomization_ShortsColor2_K2Node_ComponentBoundEvent_39_ColorChangedEvent__DelegateSignature(const struct FLinearColor& NewColor);
	void BndEvt__TeamCustomization_ShortsColor1Slider_K2Node_ComponentBoundEvent_38_OnFloatValueChangedEvent__DelegateSignature(float Value);
	void BndEvt__TeamCustomization_ShortsColor1_K2Node_ComponentBoundEvent_37_ColorChangedEvent__DelegateSignature(const struct FLinearColor& NewColor);
	void BndEvt__MM_PlayerCustomizationNew_BodySizeTabButton_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShortsPattern_3_K2Node_ComponentBoundEvent_24_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShortsPattern_2_K2Node_ComponentBoundEvent_21_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShortsPattern_1_K2Node_ComponentBoundEvent_20_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShortsPattern_K2Node_ComponentBoundEvent_19_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtColor2Slider_K2Node_ComponentBoundEvent_18_OnFloatValueChangedEvent__DelegateSignature(float Value);
	void BndEvt__TeamCustomization_ShirtColor2_K2Node_ComponentBoundEvent_17_ColorChangedEvent__DelegateSignature(const struct FLinearColor& NewColor);
	void BndEvt__TeamCustomization_ShirtPattern_4_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_3_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_2_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_1_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtPattern_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_ShirtColor1Slider_K2Node_ComponentBoundEvent_32_OnFloatValueChangedEvent__DelegateSignature(float Value);
	void BndEvt__TeamCustomization_ShirtColor1_K2Node_ComponentBoundEvent_29_ColorChangedEvent__DelegateSignature(const struct FLinearColor& NewColor);
	void Construct();
	void SetKitVariables(const struct FSP_TeamAppearance& SP_TeamAppearance);
	void UpdateTeamVariables();
	void BndEvt__TeamCustomization_SocksPatternButton_K2Node_ComponentBoundEvent_26_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_AltGK_K2Node_ComponentBoundEvent_23_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__TeamCustomization_TeamInfo_K2Node_ComponentBoundEvent_22_OnButtonClickedEvent__DelegateSignature();
	void PlayFadeOut();
	void PlayFadeIn();
	void BndEvt__PlayerCustomization_Back_K2Node_ComponentBoundEvent_16_OnButtonClickedEvent__DelegateSignature();
	void Disable();
	void Enable();
	void CalculateColorOutputs(const struct FLinearColor& Color, struct FLinearColor* ColorWheelColor, float* SliderValue, class FString* TextBoxHex);
	void CalculateLuminosityValue(const struct FLinearColor& LinearColor, float* Value);
	void CalculateColorWheelValue(const struct FLinearColor& Color, float Luminosity, struct FLinearColor* ColorOut);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TeamCustomization_C">();
	}
	static class UTeamCustomization_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTeamCustomization_C>();
	}
};

}

