#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TR_StartMenu

#include "Basic.hpp"

#include "TR_StartMenu_classes.hpp"
#include "TR_StartMenu_parameters.hpp"


namespace SDK
{

// Function TR_StartMenu.TR_StartMenu_C.ExecuteUbergraph_TR_StartMenu
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTR_StartMenu_C::ExecuteUbergraph_TR_StartMenu(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_StartMenu_C", "ExecuteUbergraph_TR_StartMenu");

	Params::TR_StartMenu_C_ExecuteUbergraph_TR_StartMenu Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TR_StartMenu.TR_StartMenu_C.BndEvt__MM_Start_No_K2Node_ComponentBoundEvent_14_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UTR_StartMenu_C::BndEvt__MM_Start_No_K2Node_ComponentBoundEvent_14_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_StartMenu_C", "BndEvt__MM_Start_No_K2Node_ComponentBoundEvent_14_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TR_StartMenu.TR_StartMenu_C.BndEvt__MM_Start_Yes_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UTR_StartMenu_C::BndEvt__MM_Start_Yes_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_StartMenu_C", "BndEvt__MM_Start_Yes_K2Node_ComponentBoundEvent_5_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TR_StartMenu.TR_StartMenu_C.BndEvt__MM_Start_Yes_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UTR_StartMenu_C::BndEvt__MM_Start_Yes_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_StartMenu_C", "BndEvt__MM_Start_Yes_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TR_StartMenu.TR_StartMenu_C.BndEvt__MM_Start_No_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void UTR_StartMenu_C::BndEvt__MM_Start_No_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_StartMenu_C", "BndEvt__MM_Start_No_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TR_StartMenu.TR_StartMenu_C.BndEvt__TR_StartMenu_No_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UTR_StartMenu_C::BndEvt__TR_StartMenu_No_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_StartMenu_C", "BndEvt__TR_StartMenu_No_K2Node_ComponentBoundEvent_13_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TR_StartMenu.TR_StartMenu_C.BndEvt__TR_StartMenu_Yes_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UTR_StartMenu_C::BndEvt__TR_StartMenu_Yes_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_StartMenu_C", "BndEvt__TR_StartMenu_Yes_K2Node_ComponentBoundEvent_12_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TR_StartMenu.TR_StartMenu_C.BndEvt__TR_StartMenu_Settings_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UTR_StartMenu_C::BndEvt__TR_StartMenu_Settings_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_StartMenu_C", "BndEvt__TR_StartMenu_Settings_K2Node_ComponentBoundEvent_11_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TR_StartMenu.TR_StartMenu_C.Disable
// (BlueprintCallable, BlueprintEvent)

void UTR_StartMenu_C::Disable()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_StartMenu_C", "Disable");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TR_StartMenu.TR_StartMenu_C.BndEvt__TR_StartMenu_Settings_1_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UTR_StartMenu_C::BndEvt__TR_StartMenu_Settings_1_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_StartMenu_C", "BndEvt__TR_StartMenu_Settings_1_K2Node_ComponentBoundEvent_10_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TR_StartMenu.TR_StartMenu_C.BndEvt__TR_StartMenu_Exit_1_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UTR_StartMenu_C::BndEvt__TR_StartMenu_Exit_1_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_StartMenu_C", "BndEvt__TR_StartMenu_Exit_1_K2Node_ComponentBoundEvent_9_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TR_StartMenu.TR_StartMenu_C.BndEvt__TR_StartMenu_GoalKeepingTutorial_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UTR_StartMenu_C::BndEvt__TR_StartMenu_GoalKeepingTutorial_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_StartMenu_C", "BndEvt__TR_StartMenu_GoalKeepingTutorial_K2Node_ComponentBoundEvent_8_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TR_StartMenu.TR_StartMenu_C.BndEvt__TR_StartMenu_KickingTutorial_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UTR_StartMenu_C::BndEvt__TR_StartMenu_KickingTutorial_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_StartMenu_C", "BndEvt__TR_StartMenu_KickingTutorial_K2Node_ComponentBoundEvent_7_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TR_StartMenu.TR_StartMenu_C.BndEvt__TR_StartMenu_DribblingTutorial_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UTR_StartMenu_C::BndEvt__TR_StartMenu_DribblingTutorial_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_StartMenu_C", "BndEvt__TR_StartMenu_DribblingTutorial_K2Node_ComponentBoundEvent_6_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TR_StartMenu.TR_StartMenu_C.BndEvt__TR_StartMenu_MovementTutorial_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UTR_StartMenu_C::BndEvt__TR_StartMenu_MovementTutorial_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_StartMenu_C", "BndEvt__TR_StartMenu_MovementTutorial_K2Node_ComponentBoundEvent_5_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TR_StartMenu.TR_StartMenu_C.Enable
// (BlueprintCallable, BlueprintEvent)

void UTR_StartMenu_C::Enable()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_StartMenu_C", "Enable");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TR_StartMenu.TR_StartMenu_C.BndEvt__TR_StartMenu_FreePlay_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UTR_StartMenu_C::BndEvt__TR_StartMenu_FreePlay_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_StartMenu_C", "BndEvt__TR_StartMenu_FreePlay_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TR_StartMenu.TR_StartMenu_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UTR_StartMenu_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_StartMenu_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TR_StartMenu.TR_StartMenu_C.ResumeEnabled
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UTR_StartMenu_C::ResumeEnabled()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_StartMenu_C", "ResumeEnabled");

	Params::TR_StartMenu_C_ResumeEnabled Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

