#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TR_Tutorial_Kicking

#include "Basic.hpp"

#include "TR_Tutorial_Kicking_classes.hpp"
#include "TR_Tutorial_Kicking_parameters.hpp"


namespace SDK
{

// Function TR_Tutorial_Kicking.TR_Tutorial_Kicking_C.ExecuteUbergraph_TR_Tutorial_Kicking
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTR_Tutorial_Kicking_C::ExecuteUbergraph_TR_Tutorial_Kicking(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_Tutorial_Kicking_C", "ExecuteUbergraph_TR_Tutorial_Kicking");

	Params::TR_Tutorial_Kicking_C_ExecuteUbergraph_TR_Tutorial_Kicking Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TR_Tutorial_Kicking.TR_Tutorial_Kicking_C.Set_ControllerMode
// (BlueprintCallable, BlueprintEvent)

void UTR_Tutorial_Kicking_C::Set_ControllerMode()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_Tutorial_Kicking_C", "Set_ControllerMode");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TR_Tutorial_Kicking.TR_Tutorial_Kicking_C.EndTutorial
// (BlueprintCallable, BlueprintEvent)

void UTR_Tutorial_Kicking_C::EndTutorial()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_Tutorial_Kicking_C", "EndTutorial");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TR_Tutorial_Kicking.TR_Tutorial_Kicking_C.BndEvt__TR_Tutorial_Movement_NextTutorial_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UTR_Tutorial_Kicking_C::BndEvt__TR_Tutorial_Movement_NextTutorial_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_Tutorial_Kicking_C", "BndEvt__TR_Tutorial_Movement_NextTutorial_K2Node_ComponentBoundEvent_2_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TR_Tutorial_Kicking.TR_Tutorial_Kicking_C.BndEvt__TR_Tutorial_Movement_ChangeTraining_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UTR_Tutorial_Kicking_C::BndEvt__TR_Tutorial_Movement_ChangeTraining_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_Tutorial_Kicking_C", "BndEvt__TR_Tutorial_Movement_ChangeTraining_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TR_Tutorial_Kicking.TR_Tutorial_Kicking_C.Disable
// (BlueprintCallable, BlueprintEvent)

void UTR_Tutorial_Kicking_C::Disable()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_Tutorial_Kicking_C", "Disable");

	UObject::ProcessEvent(Func, nullptr);
}


// Function TR_Tutorial_Kicking.TR_Tutorial_Kicking_C.Enable
// (BlueprintCallable, BlueprintEvent)

void UTR_Tutorial_Kicking_C::Enable()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("TR_Tutorial_Kicking_C", "Enable");

	UObject::ProcessEvent(Func, nullptr);
}

}

